[project]
name = "overture-serverless"
dynamic = ["version"]
description = "Base classes for portable, framework-agnostic serverless Python jobs."
authors = [
    {name = "Overture Maps Foundation"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.0.0",
]

[build-system]
requires = ["setuptools>=64.0", "setuptools_scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["overture_serverless"]

[tool.setuptools_scm]
root = ".."
tag_regex = "^overture_serverless-v(?P<version>.*)$"
git_describe_command = "git describe --dirty --tags --long --match 'overture_serverless-v*'"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["overture_serverless"]

[tool.coverage.report]
fail_under = 95
show_missing = true

[tool.semantic_release]
commit_parser = "conventional-monorepo"
tag_format = "overture_serverless-v{version}"
allow_zero_version = true

[tool.semantic_release.commit_parser_options]
path_filters = ["."]
scope_prefix = "overture_serverless"
